### ISSUE TITLE
The exon-intron structure information of the identified circRNA isoforms

### ISSUE THREAD

**Issue by chiangtw** [omiics-dk/long_read_circRNA#5]
Hi,

I’m looking for the exon-intron structure information of the identified circRNA isoforms.
Should I look into the file `$SAMPLE.circ_circRNA_exon_usage_length_of_exons.txt`?
Or could you show me how to get the information?

Thank you for you time and help.

**Comment by omiics-dk** [comment]
Hi,

Due to a bug in the code the `$SAMPLE.circ_circRNA_exon_usage_length_of_exons.txt` file was previously left empty. This has now been fixed, along with many other improvements. The `$SAMPLE.circ_circRNA_exon_usage_length_of_exons.txt` file shows exon usage levels, but only for fairly high occurrence exons. The file also shows genomic region and length of exon.

I have updated the software to version 2.1. Please get the new version.
This version also outputs bam and bigWig files. These can be viewed in a genome browser such as the IGV browser. These are likely to be better options for you to view circRNA isoform.
